server:
  port: 14512
spring:
  application:
    name: consumer-service
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: consumer-service
  registry:
    address: nacos://192.168.66.19:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: 15511

