server:
  port: 14511
spring:
  application:
    name: provider-service
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: provider-service
  registry:
    address: nacos://192.168.66.19:8848
    username: nacos
    password: nacos
  scan:
    base-packages: com.sxh.dubboprovide.impl
  protocol:
    name: dubbo
    port: 15511
